os:
  - osx

sudo: false

language: rust

rust:
  - nightly
  - beta
  - stable

before_install:
  - brew update
  - brew install openal-soft libsndfile

before_script:
  - brew uninstall libpng || true

env:
  - DYLD_LIBRARY_PATH=/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/

script:
  - |
    cargo build --verbose
    cargo test --verbose
